default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: marketplace_api_development
  host: db # localhost
  port: 5432
  username: rodolfo
  password: R0d0lf0P31x0t0

test:
  <<: *default
  database: marketplace_api_test
  host: db
  port: 5432
  username: rodolfo
  password: R0d0lf0P31x0t0

production:
  <<: *default
  database: marketplace_api_production
  username: marketplace_api
  password: <%= ENV["MARKETPLACE_API_DATABASE_PASSWORD"] %>
